name: iran_appmarket
description: A Flutter plugin to open the apps page in an iranian android market.
version: 2.0.0
homepage: https://github.com/ali2236/iran_appmarket

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  package_info_plus:
  android_intent_plus: