name: iran_appmarket
description: A Flutter plugin to open the apps page in an iranian android market.
version: 1.0.1
homepage: https://github.com/ali2236/iran_appmarket

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  package_info_plus: ^1.0.0
  android_intent: ^2.0.0