name: iran_appmarket
description: A Flutter plugin to open the apps page in an iranian android market.
version: 0.4.0
homepage: https://github.com/ali2236/iran_appmarket

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get_version: ^0.2.1
  android_intent: ^0.3.5+1