name: iran_appmarket
description: A Flutter plugin to open the apps page in an iranian android market.
version: 0.3.1
homepage: https://github.com/ali2236/iran_appmarket

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intent:
  get_version: